name: food
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  shared_preferences: ^0.5.8
  flutter_bloc: ^6.0.1
  dio: ^3.0.10
  dio_http_cache: ^0.2.9
  keyboard_dismisser: ^1.0.2
  flutter_svg: ^0.19.1
  get: ^3.13.2
  cached_network_image: ^2.3.3
  shimmer: ^1.1.1
  #flutter pub run change_app_package_name:main vn.daivp.foodedu
  change_app_package_name: ^0.1.2
  package_info: ^0.4.3
  fluttertoast: ^7.1.8
  image_picker: ^0.6.7+22

  cupertino_icons: ^1.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  retrofit_generator: ^1.3.7
  #flutter packages pub run build_runner build --delete-conflicting-outputs
  build_runner: any
  json_serializable: any
  pedantic: ^1.9.2

flutter:

  uses-material-design: true
  
  assets:
    - assets/svg/
    - assets/png/

  fonts:
    - family: AvenirNextLTPro
      fonts:
        - asset: assets/fonts/AvenirNextLTPro-Regular.ttf
          weight: 500
        - asset: assets/fonts/AvenirNextLTPro-Demi.ttf
          weight: 600
        - asset: assets/fonts/AvenirNextLTPro-Medium.ttf
          weight: 700
